_target_: src.models.resnet18.LResNet18
output_path: ${paths.dvclive_path}/plots/metrics
num_target_classes: 10

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: max
  factor: 0.1
  patience: 10
