stages:
  train:
    cmd: poetry run python src/train.py
    deps:
      - src/models
      - src/datasets
      - src/train.py
    outs:
      - output/.dvclive
      - output/checkpoints/best_model.ckpt

artifacts:
  cv-classification:
    path: output/checkpoints/best_model.ckpt
    type: model
    meta:
      framework: pytorch

params:
  - output/.dvclive/params.yaml

metrics:
  - output/.dvclive/metrics.json

plots:
  - train_loss:
      title: Train Loss
      x:
        output/.dvclive/plots/metrics/train/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/train/loss.tsv: loss
      x_label: epoch
      y_label: loss

  - train_accuracy:
      title: Train Accuracy
      x:
        output/.dvclive/plots/metrics/train/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/train/accuracy.tsv: accuracy
      x_label: epoch
      y_label: accuracy

  - train_f1:
      title: Train F1
      x:
        output/.dvclive/plots/metrics/train/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/train/f1.tsv: f1
      x_label: epoch
      y_label: f1

  - validation_loss:
      title: Validation Loss
      x:
        output/.dvclive/plots/metrics/val/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/val/loss.tsv: loss
      x_label: epoch
      y_label: loss

  - validation_accuracy:
      title: Validation Accuracy
      x:
        output/.dvclive/plots/metrics/val/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/val/accuracy.tsv: accuracy
      x_label: epoch
      y_label: accuracy

  - validation_f1:
      title: Validation F1
      x:
        output/.dvclive/plots/metrics/val/epoch.tsv: epoch
      y:
        output/.dvclive/plots/metrics/val/f1.tsv: f1
      x_label: epoch
      y_label: f1

  - confusion_matrix:
      title: Confusion Matrix
      template: confusion_normalized
      x:
        output/.dvclive/plots/metrics/test/targets.tsv: targets
      y:
        output/.dvclive/plots/metrics/test/predictions.tsv: predictions
      x_label: actual
      y_label: predicted

  - test_metrics:
      title: Test Metrics
      template: bar_horizontal
      x:
        output/.dvclive/plots/metrics/test/metrics_overview.csv: metric_value
      y:
        output/.dvclive/plots/metrics/test/metrics_overview.csv: metric
      x_label: value
      y_label: metric
