
help:
	@echo "Displaying help information..."
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

torch-info:
	@echo "Gathering information about torch installation..."
	poetry run python src/utils/rich/print_torch_info.py

clean:
	@echo "Cleaning autogenerated files..."
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs:
	@echo "Cleaning log files..."
	rm -rf .output/logs/**

format:
	@echo "Running pre-commit hooks..."
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	@echo "Syncing with main branch..."
	git pull
	git pull origin main

test:
	@echo "Running non-slow tests..."
	poetry run pytest -k "not slow"

test-full:
	@echo "Running all tests..."
	poetry run pytest

train:
	@echo "Training the model as found in /config/train.yaml..."
	dvc exp run -f
