# @package _global_

defaults:
  - paths: default
  - dataset: cifar10 # choose datamodule with `test_dataloader()` for evaluation
  - model: resnet18
  - logger: null
  - trainer: default
  - extras: default
  - hydra: default
  - _self_

task_name: "eval"

tags: ["dev"]

seed: 42
